chapphotels/chapphotels/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home, UserSignUp
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', UserSignUp.as_view(), name="signup"),
    path('', home, name='home'),
    path('rooms/', include('rooms.urls')),
    path('bookings/', include('bookings.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chapphotels/rooms/urls.py
from django.urls import path
from .views import RoomListView

urlpatterns = [
	path('list/', RoomListView.as_view(), name="room-list"),
]

chapphotels/rooms/models.py
# -*- encoding: utf-8 -*-
from django.db import models


class Room(models.Model):
    SINGLE_ROOM = 1
    DOUBLE_ROOM = 2
    EXTRA_BED_ROOM = 3
    TRIPLE_ROOM = 4
    SUITE_ROOM = 5
    MATRIMONIAL_SUITE_ROOM = 6

    RoomTypeChoices = (
        (SINGLE_ROOM, 'Habitación simple'),
        (DOUBLE_ROOM, 'Habitación doble'),
        (EXTRA_BED_ROOM, 'Habitación con cama supletoria'),
        (TRIPLE_ROOM, 'Habitación triple'),
        (SUITE_ROOM, 'Suite'),
        (MATRIMONIAL_SUITE_ROOM, 'Suite matrimonial')
    )

    room_number = models.IntegerField('Número de habitación', primary_key=True, unique=True)
    room_type = models.IntegerField('Tipo de habitación', choices=RoomTypeChoices)
    price = models.DecimalField('Precio por noche (€)', max_digits=19, decimal_places=10)
    image = models.ImageField('Imagen', upload_to='room_images/', blank=True, null=True)
    smoker = models.BooleanField('Habitación para fumadores', default=False)
    wifi = models.BooleanField('WIFI', default=False)
    air_conditioner = models.BooleanField('Aire acondicionado', default=False)
    safe_box = models.BooleanField('Caja fuerte', default=False)
    fridge = models.BooleanField('Nevera', default=False)
    viewer = models.BooleanField('Balcón', default=False)

    class Meta:
        verbose_name_plural = "Habitaciones"
        verbose_name = "Habitación"

    def get_room_type_label(self):
        for room_type in self.RoomTypeChoices:
            if self.room_type == room_type[0]:
                return room_type[1]

        return ''

chapphotels/rooms/forms.py
# -*- encoding: utf-8 -*-
from django import forms
from django.utils import timezone
from datetime import timedelta


class RoomListForm(forms.Form):
    from_date = forms.DateTimeField(required=False, widget=forms.DateInput(), initial=timezone.now())
    until_date = forms.DateTimeField(
        required=False, widget=forms.DateInput(), initial=timezone.now() + timedelta(days=5)
    )
    smoker = forms.BooleanField(required=False, label='Habitación fumadores')

    def clean(self):
        cleaned_data = super(RoomListForm, self).clean()

        from_date = cleaned_data.get('from_date')
        until_date = cleaned_data.get('until_date')

        if not from_date:
            from_date = timezone.now()

        if not until_date:
            until_date = timezone.now() + timedelta(days=5)

        from_date = from_date.replace(hour=12, minute=0, second=0)
        until_date = until_date.replace(hour=12, minute=0, second=0)

        self.fields.get('from_date').initial = from_date
        self.fields.get('until_date').initial = until_date

        self.initial['from_date'] = from_date
        self.initial['until_date'] = until_date

        cleaned_data.update({
            'from_date': from_date,
            'until_date': until_date
        })

        return cleaned_data

chapphotels/rooms/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from .models import Room
from django.db.models import Q
from .forms import RoomListForm


class RoomListView(ListView):

    model = Room
    context_object_name = 'rooms'
    template_name = 'rooms/room_list.html'
    filter_form = None

    def dispatch(self, request):
        self.filter_form = RoomListForm(request.GET)
        return super(RoomListView, self).dispatch(request=request)

    def get(self, request, *args, **kwargs):
        '''
            Overwirte this method to include form data into context
        '''
        self.object_list = self.get_queryset()
        allow_empty = self.get_allow_empty()
        if not allow_empty:
            # When pagination is enabled and object_list is a queryset,
            # it's better to do a cheap query than to load the unpaginated
            # queryset in memory.
            if self.get_paginate_by(self.object_list) is not None and hasattr(self.object_list, 'exists'):
                is_empty = not self.object_list.exists()
            else:
                is_empty = len(self.object_list) == 0
            if is_empty:(_("Empty list and '%(class_name)s.allow_empty' is False.") % {
                    'class_name': self.__class__.__name__,
                })

        context = self.get_context_data()
        context['form'] = self.filter_form
        return self.render_to_response(context)

    def get_queryset(self):
        if self.filter_form.has_changed() and self.filter_form.is_valid():
            from_date = self.filter_form.cleaned_data.get('from_date')
            until_date = self.filter_form.cleaned_data.get('until_date')
            smoker = self.filter_form.cleaned_data.get('smoker')

            from_in_range_filter = Q(booking__from_date__gte=from_date, booking__from_date__lt=until_date)
            until_in_range_filter = Q(booking__until_date__lte=until_date, booking__until_date__gt=from_date)
            range_in_middle_filter = Q(booking__from_date__lte=from_date, booking__until_date__gte=until_date)

            if smoker:
                smoker_filter = Q(smoker=smoker)
            else:
                smoker_filter = Q()

            return super(RoomListView, self).get_queryset().exclude(
                from_in_range_filter | until_in_range_filter | range_in_middle_filter
            ).filter(smoker_filter)

        return super(RoomListView, self).get_queryset()

chapphotels/rooms/templates/rooms/booking_create.html
<!-- Modal -->
<div class="modal fade" id="bookingCreateModal" tabindex="-1" role="dialog" aria-labelledby="bookingCreateModalTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Reservar</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="bookingCreateFormId" action="{% url 'booking-create' %}" method="post">{% csrf_token %}
                    <div class="row">
                        <input type="text" class="form-control" id="room_modal_id" name="room" style="display: none;">
                        <div class="col">
                            <label for="from_date" class="col-form-label">Desde:</label>
                            <input type="text" class="form-control" id="from_date_modal" name="from_date" readonly>
                        </div>
                        <div class="col">
                            <label for="until_date" class="col-form-label">Hasta:</label>
                            <input type="text" class="form-control" id="until_date_modal" name="until_date" readonly>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <label for="name" class="col-form-label">Nombre:</label>
                            <input type="text" class="form-control" id="name_modal" name="name" value="{{ user.get_username }}" disabled>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <label for="phone" class="col-form-label">Teléfono:</label>
                            <input type="number" class="form-control" id="phone_modal" name="phone">
                        </div>
                        <div class="col">
                            <label for="card_number" class="col-form-label">Número de tarjeta:</label>
                            <input type="number" class="form-control" id="card_number_modal" name="card_number">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <label for="address" class="col-form-label">Dirección:</label>
                            <input type="text" class="form-control" id="address_modal" name="address">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <label for="observations" class="col-form-label">Observaciones adicionales:</label>
                            <textarea class="form-control" id="observations_modal" rows="3" name="observations"></textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <hr>
                        <div class="row">
                            <div class="col-sm-4">
                                <label for="total" class="col-form-label"><b>Total:</b><label id="total_label_id"></label>€</label>
                            </div>
                            <div  class="text-right col-sm-8">
                                <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                                <button type="submit" class="btn btn-primary">Reservar</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

chapphotels/rooms/templates/rooms/room_list.html
{% extends "index.html" %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
	<div class="container">
		<div class="row border border-info rounded" style="">
			<div class="col-sm-1"></div>
			<div class="col-sm-4">
				<form action="{% url 'room-list' %}" method="get" class="form-horizontal" role="form">
					<div class="date form-group row {% if form.from_date.errors %}has-error{% endif %}">
					    <label for="{{ form.from_date.id_for_label }}" class="col-sm-2 col-form-label"><b>Desde:</b></label>
					    <div class="col-sm-10">
					        {% if form.from_date.errors %}
					            <span class='text-danger'>{{ form.from_date.errors|join:'<br />' }}</span>
					        {% endif %}
					        <input name="from_date"  data-format="dd/MM/yyyy" type="date" class="form-control" id="id_from_date" value="{{form.initial.from_date|date:'Y-m-d'}}">
					    </div>
					</div>
					<div class="form-group row {% if form.until_date.errors %}has-error{% endif %}">
					    <label for="{{ form.until_date.id_for_label }}" class="col-sm-2 col-form-label"><b>Hasta:</b></label>
					    <div class="col-sm-10">
					        {% if form.until_date.errors %}
					            <span class='text-danger'>{{ form.until_date.errors|join:'<br />' }}</span>
					        {% endif %}
					        <input name="until_date"  data-format="dd/MM/yyyy" type="date" class="form-control" id="id_until_date" value="{{form.initial.until_date|date:'Y-m-d'}}">
					    </div>
					</div>
					<div class="form-group">
						<div class="row">
							<div class="col-md-8">
								{{ form.smoker }} {{form.smoker.label}}
							</div>
							<div class="col-md-4">
								<button type="submit" class="btn btn-success">Buscar</button>
							</div>
						</div>
					</div>
				</form>
			</div>
			<div class="col-sm-1"></div>
		</div>
		<div class="row">
			{% for room in rooms %}
				<div class="col-lg-3 col-md-4 col-sm-6 portfolio-item" id="room-{{room.room_number}}-id">
					<div class="card h-100">
						{% if room.image %}
							<img class="card-img-top" src="{{room.image.url}}" alt="está" >
						{% else %}
							<img class="card-img-top" src="{% static "base/not_image.jpeg" %}" alt="no está">
						{% endif %}
						<div class="card-body">
							<h5 class="card-title">
								{{room.pk}}-{{ room.get_room_type_label }}
							</h5>
							<p class="card-text">
								<b>Precio: </b>{{room.price|floatformat:2}}€ por noche
							</p>
							<!-- <div class="container"> -->
								<div class="row">
									{% if room.wifi == True %}
									<div class="col-lg-3 col-md-4 col-sm-6 portfolio-item">
										<div class="card h-100">
											<img class="card-img-top" src="{% static "base/wifi_icon.png" %}" alt="wifi" data-toggle="tooltip" data-placement="top" title="Wifi">
										</div>
									</div>
									{% endif %}
									{% if room.air_conditioner == True %}
									<div class="col-lg-3 col-md-4 col-sm-6 portfolio-item">
										<div class="card h-100">
											<img class="card-img-top" src="{% static "base/Air_conditioning_icon.png" %}" alt="Aire acondicionado" data-toggle="tooltip" data-placement="top" title="Aire acondicionado">
										</div>
									</div>
									{% endif %}
									{% if room.fridge == True %}
									<div class="col-lg-3 col-md-4 col-sm-6 portfolio-item">
										<div class="card h-100">
											<img class="card-img-top" src="{% static "base/fridge_icon.png" %}" alt="Nevera" data-toggle="tooltip" data-placement="top" title="Nevera">
										</div>
									</div>
									{% endif %}	
									{% if room.safe_box == True %}
									<div class="col-lg-3 col-md-4 col-sm-6 portfolio-item">
										<div class="card h-100">
											<img class="card-img-top" src="{% static "base/safe_box_icon.png" %}" alt="Caja fuerte" data-toggle="tooltip" data-placement="top" title="Caja fuerte">
										</div>
									</div>
									{% endif %}
									{% if room.smoker == True %}
									<div class="col-lg-3 col-md-4 col-sm-6 portfolio-item">
										<div class="card h-100">
											<img class="card-img-top" src="{% static "base/smoker_icon.png" %}" alt="Fumadores" data-toggle="tooltip" data-placement="top" title="Habitación para Fumadores">
										</div>
									</div>
									{% endif %}	
									{% if room.viewer == True %}
									<div class="col-lg-3 col-md-4 col-sm-6 portfolio-item">
										<div class="card h-100">
											<img class="card-img-top" src="{% static "base/views_icon.png" %}" alt="Balcón" data-toggle="tooltip" data-placement="top" title="Balcón/Terraza">
										</div>
									</div>
									{% endif %}	
								</div>
							<!-- </div> -->
						</div>
						<div class="card-footer">
							<b>Mejor precio</b>
							{% if user.is_authenticated %}
					    		<button class="btn btn-primary" style="position:absolute;right:5px;bottom:5px;" onclick="return bookingButtonClick({{room.room_number}},{{room.price}})">Reservar</button>
					    	{% else %}
					    		<td><a href="{% url 'login' %}" class="btn btn-primary" style="position:absolute;right:5px;bottom:5px;">Reservar</a></td>
					    	{% endif %}
					    </div>
					</div>
				</div>
			{% empty %}
	    		<li>No se escontraron habitaciones disponibles.</li>
			{% endfor %}
		</div>
	</div>

	{% include "./booking_create.html" %}
{% endblock %}

room_number
room_type
price